workflows:
  android-build:
    name: Android Build & Test

    instance_type: mac_mini_m2

    environment:
      groups:
        - android

    scripts:
      - name: Create local.properties file
        script: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
      
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew

      - name: Run Tests and Build Debug APK
        script: |
          ./gradlew testDebugUnitTest assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk