name: Release Build & TG Deploy

on:
  pull_request:
    types: [closed]
    branches: [ "main", "master" ]

jobs:
  build-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: |
        set -o pipefail
        ./gradlew assembleRelease -PversionCode=${{ github.run_number }} 2>&1 | tee build.log

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app 
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        buildToolsVersion: 36.0.0

    - name: Send Signed Release APK to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: ${{steps.sign_app.outputs.signedReleaseFile}}
        message: "🎉 Новый Релиз (Версия: 1.0.${{ github.run_number }})!"

    - name: Extract Error Log
      if: failure()
      run: |
        echo "ERROR_LOG<<EOF" >> $GITHUB_ENV
        tail -n 30 build.log >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Notify Telegram on Failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ❌ Ошибка сборки Релиза! 
          Версия: 1.0.${{ github.run_number }}
          Автор: ${{ github.actor }}
          
          📝 Последние строки лога:
          `${{ env.ERROR_LOG }}`
          
          🔍 Полные логи: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}